version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - DATABASE_URL=postgres://neondb_owner:npg_h3HgPyqM0kse@ep-withered-pond-a9sxaz90-pooler.gwc.azure.neon.tech/neondb?sslmode=require 