services:
  - type: web
    name: proyecto-integrado
    env: php
    buildCommand: composer install
    startCommand: vendor/bin/heroku-php-apache2
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://proyecto-integrado-rouge.vercel.app
      - path: /*
        name: Access-Control-Allow-Methods
        value: GET, POST, OPTIONS
      - path: /*
        name: Access-Control-Allow-Headers
        value: Content-Type, Authorization, X-Requested-With
      - path: /*
        name: Access-Control-Max-Age
        value: "86400" 